### PR TITLE
Update Node Client

### PR DESCRIPTION
**Pull request by zbialecki**
- Update Babel to latest version and fix build script
- Fix calls to comparisons API by updating the structure of the request body

### CODE REVIEW

**Comment by jamespayor** [comment]
@zbialecki if I remember correctly, I needed to have a flat request body for the case of uploading files (which requires a multipart request). Did you test performing a comparison with file upload?

Unfortunately I'm on holidays, so it might be a few days before I can test things myself.

**Comment by bentoner** [comment]
@zbialecki Thanks very much.

@jamespayor do you have a preferred way to add tests? ~~I was thinking of creating a special test account and just making its auth key public.~~ Do you think we need to test against the live API or is mocking it enough?

**Comment by bentoner** [comment]
@jamespayor I started on a simple test script at https://github.com/draftable/compare-api-node-client/commits/tests.

Current status:
* creation works with Zach's patch for files specified by URL (and it doesn't work without it)
* the test for creation via buffers fails (either way)
* the test for deletion fails

I haven't tested viewer URL generation yet.

**Comment by bentoner** [comment]
I completed the test script and fixed everything.

**Comment by jamespayor** [comment]
Great! Thanks for the pull request @zbialecki.

**Comment by zbialecki** [comment]
Awesome! Thanks @bentoner and @jamespayor. Are you planning a new release to NPM soon?

**Comment by jamespayor** [comment]
@zbialecki yes! Should be a new release shortly (probably tomorrow).

**Comment by jamespayor** [comment]
@zbialecki fyi, 1.1.0 is released now.

**Pull request merged**
